# Generated by Django 4.1.3 on 2022-12-11 13:36

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountsUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="이름")),
                (
                    "role",
                    models.CharField(default="user", max_length=16, verbose_name="역할"),
                ),
                ("birth", models.DateField(verbose_name="생년월일")),
                ("phone", models.CharField(max_length=11, verbose_name="전화번호")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="주소"
                    ),
                ),
                (
                    "sleep_yn",
                    models.BooleanField(default=False, verbose_name="장기불참 여부"),
                ),
                (
                    "sleep_reason",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="장기불참 사유"
                    ),
                ),
                (
                    "expected_return_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="예정 복귀일"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "유저 정보2",
                "verbose_name_plural": "유저 정보2",
                "db_table": "accounts_user",
            },
        ),
    ]
